source('spark_init.R')
sales.shoes <- jsonFile(sqlContext, '/data/input/bob1/sales_shoes_datewise_data')
sales.shoes.train <- subset(sales.shoes, sales.shoes$created_at < '2015-07-01')
sales.shoes.test <- subset(sales.shoes, sales.shoes$created_at >= '2015-07-01' & sales.shoes$created_at < '2015-10-01')
count(sales.shoes.test)
customers.train <- distinct(select(sales.shoes.train, 'fk_customer'))
customers.test <- distinct(select(sales.shoes.test, 'fk_customer'))
count(customers.test)
customers.returning <- intersect(customers.train, customers.test)
count(customers.returning)
customers.firsttime <- except(customers.test, customers.returning)
count(customers.firsttime)
returns.shoes <- jsonFile(sqlContext, '/data/input/crm/returns_shoes_data')
registerTempTable(sales.shoes.test, 'sales_shoes_test')
registerTempTable(returns.shoes, 'returns_shoes')
registerTempTable(customers.returning, 'customers_returning')
registerTempTable(customers.firsttime, 'customers_firsttime')
count.sales.returning <- sql(sqlContext, 'select count(id_sales_order_item) from sales_shoes_test sales, customers_returning cr where sales.fk_customer = cr.fk_customer')
showDF(count.sales.returning)
count.sales.firsttime <- sql(sqlContext, 'select count(id_sales_order_item) from sales_shoes_test sales, customers_firsttime cf where sales.fk_customer = cf.fk_customer')
showDF(count.sales.firsttime)
count.returns.returning <- sql(sqlContext, 'select count(id_sales_order_item) from sales_shoes_test sales, returns_shoes returns, customers_returning cr where sales.fk_customer = cr.fk_customer and sales.id_sales_order_item = returns.productid and lower(returns.returnreason) like "%size%"')
showDF(count.returns.returning)
count.returns.firsttime <- sql(sqlContext, 'select count(id_sales_order_item) from sales_shoes_test sales, returns_shoes returns, customers_firsttime cf where sales.fk_customer = cf.fk_customer and sales.id_sales_order_item = returns.productid and lower(returns.returnreason) like "%size%"')
showDF(count.returns.firsttime)
count.returns.shoes <- sql(sqlContext, 'select count(id_sales_order_item) from sales_shoes_test sales, returns_shoes returns where sales.id_sales_order_item = returns.productid and lower(returns.returnreason) like "%size%"')
showDF(count.returns.shoes)
